# Generated by Django 5.2.15 on 2026-06-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_service'),
        ('services', '0002_servicecategory_serviceitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
