# Generated by Django 5.2.15 on 2026-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
