# Generated by Django 5.2.15 on 2026-06-17 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_serviceitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicecategory'),
        ),
    ]
