# Generated by Django 5.2.15 on 2026-06-17 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_serviceitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
