# Generated by Django 5.2.15 on 2026-06-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_shop_created_at_remove_shop_owner_name_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('shop', 'phone'), name='unique_customer_phone_per_shop'),
        ),
    ]
