# Generated by Django 5.2.15 on 2026-06-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_unique_customer_phone_per_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='receipt_footer',
            field=models.TextField(blank=True, default='Thank you for choosing us.'),
        ),
        migrations.AddField(
            model_name='shop',
            name='whatsapp_template',
            field=models.TextField(blank=True, default='Dear {customer}, your laundry order #{order} is ready for collection. Total Amount: {amount} OMR.'),
        ),
    ]
