# Generated by Django 5.2.15 on 2026-06-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_shop_address_shop_phone_shop_receipt_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='default_delivery_days',
            field=models.IntegerField(default=3),
        ),
    ]
