# Generated by Django 5.2.15 on 2026-06-14 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='shop',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customers.shop'),
        ),
    ]
