# Generated by Django 5.2.15 on 2026-06-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
