# Generated by Django 5.2.15 on 2026-06-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_shop_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='country',
            field=models.CharField(default='Oman', max_length=50),
        ),
        migrations.AddField(
            model_name='shop',
            name='currency',
            field=models.CharField(default='OMR', max_length=10),
        ),
        migrations.AddField(
            model_name='shop',
            name='decimal_places',
            field=models.IntegerField(default=3),
        ),
    ]
