# Generated by Django 5.2.15 on 2026-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='whatsapp_country_code',
            field=models.CharField(default='968', max_length=5),
        ),
    ]
