# Generated by Django 5.2.15 on 2026-06-07 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_item_name_orderitem_service'),
        ('services', '0002_servicecategory_serviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceitem'),
        ),
    ]
