# Generated by Django 5.2.15 on 2026-06-07 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('ready', 'Ready'), ('picked', 'Picked Up')], default='received', max_length=20),
        ),
    ]
