# Generated by Django 5.2.15 on 2026-06-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_amount_paid_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('ready', 'Ready'), ('partial', 'Partially Picked Up'), ('picked', 'Picked Up')], default='received', max_length=20),
        ),
    ]
