# Generated by Django 5.2.15 on 2026-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_orderitem_delivered_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('ready', 'Ready'), ('partial', 'Partially Picked Up'), ('picked', 'Delivered')], default='received', max_length=20),
        ),
    ]
