# Generated by Django 5.2.15 on 2026-06-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_deleted_at_order_deleted_by_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
